### ISSUE TITLE
Rust 实现Remix File

### ISSUE THREAD

**Issue by devillove084** [wuxb45/remixdb#4]
您好，不知道这样是否冒昧，我在计划使用rust实现一个数据库，看了您remixdb的论文觉得非常牛逼，我想把这个设计引入到我的设计中，您看如果方便的话，能否给一个您的邮箱或者微信，有一些问题想要请教，可以随时沟通。

**Comment by devillove084** [comment]
Hello, our team is now implementing a database. After reading your paper, we found that your paper is very awesome. We want to use rust to implement a code logic for your paper, and add multiple features at the same time. Can you give me an e-mail address ？ To facilitate real-time communication.

**Comment by devillove084** [comment]
Hello, our team is now implementing a database. After reading your paper, we found that your paper is very awesome. We want to use rust to implement a code logic for your paper, and add multiple features at the same time. Can you give me an e-mail address or wechat？ To facilitate real-time communication.

**Comment by wuxb45** [comment]
You can email me at wuxb#uic.edu. Thanks.
