### ISSUE TITLE
About the index file

### ISSUE THREAD

**Issue by Nakamotto** [wuxb45/remixdb#6]
Hello！ I am excited to read your paper.
But may i ask some questions?
Where are the remix index files stored?
I opened up wal1 but only found the key-value pairs.
what is 000.ssty used for?
I observed that the content in that file are constant.

**Comment by wuxb45** [comment]
Hello,
.ssty files are REMIX index files you're looking for.
.sstx files are the actual run data.
wal* is the write ahead log.

**Comment by Nakamotto** [comment]
Thanks for your answer！
I am a beginner to LSM-tree-based storage engine. 
Reading and understanding the source code of REMIX is pretty challenging for me.
May i ask you for some recommended papers or some tiny projects for my deeper learning？
