### ISSUE TITLE
How to configure more background threads for RemixDB?

### ISSUE THREAD

**Issue by zjs1224522500** [wuxb45/remixdb#7]
- How to configure more background threads for RemixDB? (not only for 4 threads)
- I noticed that the parameter `nr_workers` may be threads number of background threads, but I also found a macro named `XDB_COMP_CONC`. Do I need to change both values, or any other values except these two?
- I tried to change both values to 16 and found that the actual number of running threads changes frequently. I am not sure if it is correct and expected in the REMIX design.

**Comment by wuxb45** [comment]
The compaction threads are created for each compaction, so you see the number going up and down.

**Comment by wuxb45** [comment]
You're right about changing both at the same time.
